id = "air_cutter"
type = "flying"
category = "special"
pp = 15
effects = []

[power]
regular = 60
agile = 45
strong = 75

[accuracy]
regular = 95
agile = 95
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 1
agile = 1
strong = 2
