id = "astonish"
type = "ghost"
category = "physical"
pp = 25
effects = []

[power]
regular = 30
agile = 20
strong = 40

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 3
agile = 5
strong = 3

[crit_stage]
regular = 0
agile = 0
strong = 0
