id = "bite"
type = "dark"
category = "physical"
pp = 20
effects = []

[power]
regular = 60
agile = 45
strong = 75

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 3
agile = 5
strong = 3

[crit_stage]
regular = 0
agile = 0
strong = 0
