id = "charge_beam"
type = "electric"
category = "special"
pp = 15

[power]
regular = 50
agile = 40
strong = 60

[accuracy]
regular = 90
agile = 90
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "user"
status_options = ["power_boost"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 50
agile = 50
strong = 100
