id = "cross_poison"
type = "poison"
category = "physical"
pp = 15

[power]
regular = 70
agile = 55
strong = 85

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 1
agile = 1
strong = 2

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["poison"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 20
agile = 20
strong = 40
