id = "crush_grip"
type = "normal"
category = "physical"
pp = 5
effects = []

[power]
regular = 100
agile = 80
strong = 120

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 3
agile = 5
strong = 3

[crit_stage]
regular = 0
agile = 0
strong = 0
