id = "dark_void"
type = "dark"
category = "status"
pp = 10

[power]
regular = 0
agile = 0
strong = 0

[accuracy]
regular = 90
agile = 90
strong = 100

[user_action_time]
regular = 5
agile = 2
strong = 8

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["drowsy"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["guard_drop"]

[effects.duration]
regular = 3
agile = 2
strong = 4
