id = "dazzling_gleam"
type = "fairy"
category = "special"
pp = 10
effects = []

[power]
regular = 75
agile = 60
strong = 90

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0
