id = "double-edge"
type = "normal"
category = "physical"
pp = 5

[power]
regular = 100
agile = 80
strong = 120

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "recoil"
percent_of = "damage_dealt"

[effects.percent]
regular = 33
agile = 33
strong = 50
