id = "draco_meteor"
type = "dragon"
category = "special"
pp = 5

[power]
regular = 110
agile = 90
strong = 130

[accuracy]
regular = 90
agile = 90
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "user"
status_options = ["power_drop"]

[effects.duration]
regular = 3
agile = 3
strong = 3
