id = "dragon_pulse"
type = "dragon"
category = "special"
pp = 10
effects = []

[power]
regular = 80
agile = 60
strong = 100

[accuracy]
regular = 101
agile = 101
strong = 101

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0
