id = "draining_kiss"
type = "fairy"
category = "special"
pp = 15

[power]
regular = 50
agile = 40
strong = 60

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "heal"
percent_of = "damage_dealt"

[effects.percent]
regular = 75
agile = 75
strong = 100
