id = "esper_wing"
type = "psychic"
category = "special"
pp = 10
effects = []

[power]
regular = 75
agile = 60
strong = 90

[accuracy]
regular = 90
agile = 90
strong = 100

[user_action_time]
regular = -4
agile = -4
strong = 2

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 1
agile = 1
strong = 2
