id = "giga_impact"
type = "normal"
category = "physical"
pp = 5
effects = []

[power]
regular = 120
agile = 100
strong = 150

[accuracy]
regular = 90
agile = 90
strong = 95

[user_action_time]
regular = 5
agile = 2
strong = 8

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0
