id = "head_smash"
type = "rock"
category = "physical"
pp = 5

[power]
regular = 120
agile = 100
strong = 150

[accuracy]
regular = 80
agile = 80
strong = 90

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "recoil"
percent_of = "damage_dealt"

[effects.percent]
regular = 50
agile = 50
strong = 75
