id = "hex"
type = "ghost"
category = "special"
pp = 15

[power]
regular = 65
agile = 50
strong = 80

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "multiply_power"
multiplier = 2

[effects.condition.target]
status = ["poison", "burn", "frostbite", "paralysis", "drowsy"]
