id = "hidden_power"
type = "normal"
category = "special"
pp = 15
effects = []

[power]
regular = 50
agile = 30
strong = 70

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0
