id = "ice_shard"
type = "ice"
category = "physical"
pp = 20
effects = []

[power]
regular = 40
agile = 30
strong = 50

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = -4
agile = -4
strong = 2

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0
