id = "ice_ball"
type = "ice"
category = "physical"
pp = 20

[power]
regular = 40
agile = 30
strong = 50

[accuracy]
regular = 90
agile = 90
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "user"
status_options = ["fixated"]

[effects.duration]
regular = 100
agile = 100
strong = 100

[effects.chance]
regular = 100
agile = 100
strong = 100
