id = "leaf_blade"
type = "grass"
category = "physical"
pp = 10
effects = []

[power]
regular = 85
agile = 65
strong = 105

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 1
agile = 1
strong = 2
