id = "magma_storm"
type = "fire"
category = "special"
pp = 5

[power]
regular = 90
agile = 70
strong = 110

[accuracy]
regular = 75
agile = 75
strong = 90

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["burn"]

[effects.duration]
regular = 3
agile = 2
strong = 4
