id = "mountain_gale"
type = "ice"
category = "physical"
pp = 5
effects = []

[power]
regular = 100
agile = 80
strong = 120

[accuracy]
regular = 85
agile = 85
strong = 95

[user_action_time]
regular = 5
agile = 2
strong = 8

[target_action_time]
regular = 3
agile = 5
strong = 3

[crit_stage]
regular = 0
agile = 0
strong = 0
