id = "mud_bomb"
type = "ground"
category = "special"
pp = 15

[power]
regular = 65
agile = 50
strong = 80

[accuracy]
regular = 85
agile = 85
strong = 95

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "user"
status_options = ["obscured"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 100
agile = 100
strong = 100
