id = "poison_gas"
type = "poison"
category = "status"
pp = 20

[power]
regular = 0
agile = 0
strong = 0

[accuracy]
regular = 90
agile = 90
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["poison"]

[effects.duration]
regular = 5
agile = 3
strong = 7

[effects.chance]
regular = 100
agile = 100
strong = 100
