id = "poison_sting"
type = "poison"
category = "physical"
pp = 20

[power]
regular = 30
agile = 20
strong = 40

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["poison"]

[effects.duration]
regular = 5
agile = 3
strong = 7

[effects.chance]
regular = 50
agile = 50
strong = 100
