id = "roar_of_time"
type = "dragon"
category = "special"
pp = 5

[power]
regular = 120
agile = 100
strong = 150

[accuracy]
regular = 90
agile = 90
strong = 100

[user_action_time]
regular = 5
agile = 2
strong = 8

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "modify_data"

[effects.power]
regular = 140
agile = 120
strong = 170

[effects.accuracy]
regular = 75
agile = 75
strong = 85

[effects.user_action_time]
regular = 6
agile = 4
strong = 10

[effects.condition.user]
species = "dialga-origin"
