id = "seed_flare"
type = "grass"
category = "special"
pp = 5

[power]
regular = 100
agile = 80
strong = 120

[accuracy]
regular = 85
agile = 85
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["guard_drop"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 20
agile = 20
strong = 40
