id = "shadow_force"
type = "ghost"
category = "physical"
pp = 5

[power]
regular = 100
agile = 80
strong = 120

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 3
agile = 1
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "user"
status_options = ["obscured"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 100
agile = 100
strong = 100

[[effects]]
effect_type = "modify_data"

[effects.power]
regular = 120
agile = 100
strong = 150

[effects.accuracy]
regular = 80
agile = 80
strong = 90

[effects.user_action_time]
regular = 5
agile = 2
strong = 8

[effects.condition.user]
species = "giratina-origin"
