id = "springtide_storm"
type = "fairy"
category = "special"
pp = 5

[power]
regular = 95
agile = 75
strong = 115

[accuracy]
regular = 80
agile = 80
strong = 90

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "user"
status_options = ["power_boost"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 30
agile = 30
strong = 50

[effects.condition.user]
species = "enamorous-incarnate"

[[effects]]
effect_type = "apply_status"
to = "user"
status_options = ["guard_boost"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 30
agile = 30
strong = 50

[effects.condition.user]
species = "enamorous-incarnate"

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["power_drop"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 30
agile = 30
strong = 50

[effects.condition.user]
species = "enamorous-therian"

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["guard_drop"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 30
agile = 30
strong = 50

[effects.condition.user]
species = "enamorous-therian"
