id = "volt_tackle"
type = "electric"
category = "physical"
pp = 5

[power]
regular = 120
agile = 100
strong = 140

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = 0
agile = 0
strong = 5

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "apply_status"
to = "target"
status_options = ["paralysis"]

[effects.duration]
regular = 3
agile = 2
strong = 4

[effects.chance]
regular = 30
agile = 30
strong = 50

[[effects]]
effect_type = "recoil"
percent_of = "damage_dealt"

[effects.percent]
regular = 33
agile = 33
strong = 50

[[effects]]
effect_type = "cure_status"
of = "user"
statuses = ["drowsy"]
