id = "wave_crash"
type = "water"
category = "physical"
pp = 10

[power]
regular = 75
agile = 60
strong = 90

[accuracy]
regular = 100
agile = 100
strong = 100

[user_action_time]
regular = -4
agile = -4
strong = 2

[target_action_time]
regular = 0
agile = 3
strong = 0

[crit_stage]
regular = 0
agile = 0
strong = 0

[[effects]]
effect_type = "recoil"
percent_of = "damage_dealt"

[effects.percent]
regular = 33
agile = 33
strong = 50
