id = "frostbite"
volatility = "non_volatile"
immune_types = ["ice"]

[[effects]]
effect_type = "turn_end_damage_fraction"
fraction_denominator = 12

[[effects]]
effect_type = "damage_multiplier"
side = "user"
multiplier = 0.5
move_category = "special"
